# Generated by Django 4.1.3 on 2022-12-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_list_options_rename_content_list_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.RemoveField(
            model_name='list',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='list',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='list',
            name='item_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='list',
            name='item_name',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
