# Generated by Django 4.1.3 on 2022-12-21 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_list_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_done',
            new_name='done',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_name',
            new_name='item',
        ),
    ]
