# Generated by Django 4.1.3 on 2022-12-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_item_done_item_done_and_more'),
    ]

    operations = [

    ]
