# Generated by Django 4.1.3 on 2022-12-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_list_item'),
    ]

    operations = [

    ]
