# Generated by Django 4.1.3 on 2022-12-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_item_quantity'),
    ]

    operations = [

    ]
