# Generated by Django 4.1.3 on 2022-12-23 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_list_item'),
    ]

    operations = [

    ]
