# Generated by Django 4.1.3 on 2022-12-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_list_item'),
    ]

    operations = [

    ]
