# Generated by Django 4.1.3 on 2022-12-23 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_rename_item_item_name_item_eachitem'),
    ]

    operations = [

    ]
