# Generated by Django 4.1.3 on 2022-12-23 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_delete_item_list_date_list_list_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='items',
        ),
    ]
