# Generated by Django 4.1.3 on 2023-01-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_list_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.TextField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='list',
            name='item',
            field=models.ManyToManyField(to='shop.item'),
        ),
    ]
