# Generated by Django 4.1.3 on 2023-01-04 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_item_alter_list_description_list_item'),
    ]

    operations = [
   
    ]
