# Generated by Django 4.1.3 on 2023-01-04 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_item_quantity'),
    ]

    operations = [
        
    ]
