# Generated by Django 4.1.3 on 2023-01-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_item_name_remove_list_item_list_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='item',
        ),
        migrations.AddField(
            model_name='list',
            name='item',
            field=models.ManyToManyField(to='shop.item'),
        ),
    ]
