# Generated by Django 4.1.3 on 2023-01-05 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_remove_list_item_list_item'),
    ]

    operations = [
     
    ]
