# Generated by Django 4.1.3 on 2023-01-05 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_alter_item_name_remove_list_item_list_item'),
    ]

    operations = [

    ]
