# Generated by Django 4.1.3 on 2023-01-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_alter_list_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='item',
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.TextField(default=None, max_length=50),
        ),
    ]
