# Generated by Django 4.1.3 on 2023-01-05 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_list_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item'),
        ),
    ]
