# Generated by Django 4.1.3 on 2023-01-06 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_alter_list_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None, max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item')),
            ],
        ),
    ]
