# Generated by Django 4.1.3 on 2023-01-06 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_shoppingitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitems',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.list'),
        ),
    ]
