# Generated by Django 4.1.3 on 2023-01-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_alter_shoppingitems_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingItems',
            new_name='ShoppingItem',
        ),
    ]
