# Generated by Django 4.1.3 on 2023-01-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_rename_shoppingitems_shoppingitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None, max_length=50)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='itemsbuy',
            field=models.ManyToManyField(to='shop.itemsbuy'),
        ),
    ]
