# Generated by Django 4.1.3 on 2023-01-08 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_itemsbuy_list_itemsbuy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingItem',
        ),
    ]
