# Generated by Django 4.1.3 on 2023-01-08 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_delete_shoppingitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='items',
        ),
    ]
