# Generated by Django 4.1.3 on 2023-01-08 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_delete_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemsBuy',
            new_name='Items',
        ),
    ]
