# Generated by Django 4.1.3 on 2023-01-08 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_rename_itemsbuy_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='date',
            new_name='dueDate',
        ),
    ]
