# Generated by Django 4.1.3 on 2023-01-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_item_remove_list_itemsbuy_delete_items_item_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='list_items',
        ),
        migrations.AlterField(
            model_name='list',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
